apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
    name: cache-fn
spec:
    gateway: kyma-gateway.kyma-system.svc.cluster.local
    host: books
    rules:
        - accessStrategies:
            - handler: allow
          methods:
            - GET
            - POST
          path: /.*
    service:
        name: cache-fn
        namespace: default
        port: 80