apiVersion: operator.kyma-project.io/v1beta2
kind: Kyma
metadata:
  name: default
  namespace: kyma-system
spec:
  channel: fast
  modules:
  - name: api-gateway
  - name: btp-operator
  - name: serverless
  - name: telemetry
  - name: istio

