apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: actions-oidc:repo:kwiatekus/kyma-demo:ref:refs/heads/main
    apiGroup: rbac.authorization.k8s.io
