apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: hana
spec:
  serviceOfferingName: hana-cloud
  servicePlanName: hana
  externalName: hana
  parameters:
    data:
      memory: 30
      vcpu: 2
      whitelistIPs: ["0.0.0.0/0"]
      generateSystemPassword: true
      edition: "cloud"
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: hana
spec:
  serviceInstanceName: hana
  externalName: hana
  secretName: hana
  parameters:
    scope: administration
    credential-type: PASSWORD_GENERATED
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: hana-url
spec:
  serviceInstanceName: hana
  externalName: hana-url
  secretName: hana-url