apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: hana
spec:
  serviceOfferingName: hana-cloud
  servicePlanName: hana
  externalName: hana
  parameters:
    data:
      memory: 32
      vcpu: 2
      whitelistIPs: ["0.0.0.0/0"]
      generateSystemPassword: true
      edition: "cloud"
