apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: bookstore-api
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: bookstore
  service:
    name: bookstore-service
    namespace: default
    port: 80
  rules:
    - path: /.*
      methods: ["GET"] 
      accessStrategies:
      - handler: noop
    - path: /.*
      methods: ["POST"]
      accessStrategies:
      - handler: noop
      # - handler: jwt
      #   config:
      #     jwks_urls:
      #     - https://kymagoattest.accounts400.ondemand.com/oauth2/certs