apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  labels:
    app: bookstore-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: bookstore-service
    example: bookstore-service