apiVersion: v1
kind: ConfigMap
metadata:
  name: hana-hdi-job-src
data:
  books.hdbtable: |
    COLUMN TABLE "kyma-demo.db::books" 
      (
        "id" INTEGER, 
        "title" VARCHAR(100),
        "author" VARCHAR(100),
        PRIMARY KEY ("id") 
      )
  books.hdbtabledata: |
    {
      "format_version": 1,
      "imports": [
        {
          "target_table": "kyma-demo.db::books",
          "source_data": {
            "data_type": "CSV",
            "file_name": "kyma-demo.db::books.csv",
            "has_header": true,
            "type_config": {
              "delimiter": ",",
              "do_quote": true
            }
          },
          "import_settings": {
            "import_columns": [
              "id",
              "title",
              "author"
            ]
          }
        }
      ]
    }
  books.csv: |
    id,title,author
    1,Dune,Frank Herbert
    2,Pipi Goes On Board,Astrid Lindgren
  .hdinamespace: |-
    {
      "name": "kyma-demo.db",
      "subfolder": "append"
    }
  .hdiconfig: |-
    {
      "minimum_feature_version": "1000",
      "file_suffixes": {
        "hdbapplicationtime": {
          "plugin_name": "com.sap.hana.di.applicationtime"
        },
        "hdbcalculationview": {
          "plugin_name": "com.sap.hana.di.calculationview"
        },
        "hdbconstraint": {
          "plugin_name": "com.sap.hana.di.constraint"
        },
        "txt": {
          "plugin_name": "com.sap.hana.di.copyonly"
        },
        "hdbdropcreatetable": {
          "plugin_name": "com.sap.hana.di.dropcreatetable"
        },
        "hdbflowgraph": {
          "plugin_name": "com.sap.hana.di.flowgraph"
        },
        "hdbfunction": {
          "plugin_name": "com.sap.hana.di.function"
        },
        "hdbgraphworkspace": {
          "plugin_name": "com.sap.hana.di.graphworkspace"
        },
        "hdbindex": {
          "plugin_name": "com.sap.hana.di.index"
        },
        "hdblibrary": {
          "plugin_name": "com.sap.hana.di.library"
        },
        "hdblogicalschema": {
          "plugin_name": "com.sap.hana.di.logicalschema"
        },
        "hdbprocedure": {
          "plugin_name": "com.sap.hana.di.procedure"
        },
        "hdbprojectionview": {
          "plugin_name": "com.sap.hana.di.projectionview"
        },
        "hdbprojectionviewconfig": {
          "plugin_name": "com.sap.hana.di.projectionview.config"
        },
        "hdbreptask": {
          "plugin_name": "com.sap.hana.di.reptask"
        },
        "hdbresultcache": {
          "plugin_name": "com.sap.hana.di.resultcache"
        },
        "hdbrole": {
          "plugin_name": "com.sap.hana.di.role"
        },
        "hdbroleconfig": {
          "plugin_name": "com.sap.hana.di.role.config"
        },
        "hdbsearchruleset": {
          "plugin_name": "com.sap.hana.di.searchruleset"
        },
        "hdbsequence": {
          "plugin_name": "com.sap.hana.di.sequence"
        },
        "hdbanalyticprivilege": {
          "plugin_name": "com.sap.hana.di.analyticprivilege"
        },
        "hdbview": {
          "plugin_name": "com.sap.hana.di.view"
        },
        "hdbstatistics": {
          "plugin_name": "com.sap.hana.di.statistics"
        },
        "hdbstructuredprivilege": {
          "plugin_name": "com.sap.hana.di.structuredprivilege"
        },
        "hdbsynonym": {
          "plugin_name": "com.sap.hana.di.synonym"
        },
        "hdbsynonymconfig": {
          "plugin_name": "com.sap.hana.di.synonym.config"
        },
        "hdbsystemversioning": {
          "plugin_name": "com.sap.hana.di.systemversioning"
        },
        "hdbtable": {
          "plugin_name": "com.sap.hana.di.table"
        },
        "hdbmigrationtable": {
          "plugin_name": "com.sap.hana.di.table.migration"
        },
        "hdbtabletype": {
          "plugin_name": "com.sap.hana.di.tabletype"
        },
        "hdbtabledata": {
          "plugin_name": "com.sap.hana.di.tabledata"
        },
        "csv": {
          "plugin_name": "com.sap.hana.di.tabledata.source"
        },
        "properties": {
          "plugin_name": "com.sap.hana.di.tabledata.properties"
        },
        "tags": {
          "plugin_name": "com.sap.hana.di.tabledata.properties"
        },
        "hdbtrigger": {
          "plugin_name": "com.sap.hana.di.trigger"
        },
        "hdbvirtualfunction": {
          "plugin_name": "com.sap.hana.di.virtualfunction"
        },
        "hdbvirtualfunctionconfig": {
          "plugin_name": "com.sap.hana.di.virtualfunction.config"
        },
        "hdbvirtualpackagehadoop": {
          "plugin_name": "com.sap.hana.di.virtualpackage.hadoop"
        },
        "hdbvirtualpackagesparksql": {
          "plugin_name": "com.sap.hana.di.virtualpackage.sparksql"
        },
        "hdbvirtualprocedure": {
          "plugin_name": "com.sap.hana.di.virtualprocedure"
        },
        "hdbvirtualprocedureconfig": {
          "plugin_name": "com.sap.hana.di.virtualprocedure.config"
        },
        "hdbvirtualtable": {
          "plugin_name": "com.sap.hana.di.virtualtable"
        },
        "hdbvirtualtableconfig": {
          "plugin_name": "com.sap.hana.di.virtualtable.config"
        }
      }
    }